version: "3.5"
services:
  app:
    container_name: sentio-composer-app
    image: poytr1/sentio-composer-app:latest
    restart: always
    volumes:
      - ./config.toml:/app/config.toml
      - ./.move-modules-cache:/app/.move-modules-cache
    environment:
      - BIN_PATH=/app/view-function
    ports:
      - 8080:4000