version: "3.5"
services:
  app:
    container_name: sentio-composer-server
    image: poytr1/sentio-composer-server:latest
    restart: always
    build: .
    environment:
      - BIN_PATH=/app/view-function
    ports:
      - 4000:4000